# Generated by Django 3.1.2 on 2020-11-19 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 14, 4, 24, 212140, tzinfo=utc)),
        ),
    ]
