# Generated by Django 3.1.2 on 2020-11-21 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201120_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 35, 20, 279175, tzinfo=utc)),
        ),
    ]
