# Generated by Django 3.1.2 on 2020-11-26 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201121_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='responding_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 11, 32, 3, 560207, tzinfo=utc)),
        ),
    ]
